
export let activities: any[] = [
  {title: 'Community X has a new member',
  description: '👋 Say hi to Luis Pperino Pomodoro !',
  when: '2 hs ago'},
  {title: 'Community X has a new member',
  description: '👋 Say hi to Luis Pperino Pomodoro !',
  when: '2 hs ago'},
  {title: 'Community X has a new member',
  description: '👋 Say hi to Luis Pperino Pomodoro !',
  when: '2 hs ago'},
  {title: 'Community X has a new member',
  description: '👋 Say hi to Luis Pperino Pomodoro !',
  when: '2 hs ago'},
  {title: 'Community X has a new member',
  description: '👋 Say hi to Luis Pperino Pomodoro !',
  when: '2 hs ago'},
  {title: 'Community X has a new member',
  description: '👋 Say hi to Luis Pperino Pomodoro !',
  when: '2 hs ago'},
  {title: 'Community X has a new member',
  description: '👋 Say hi to Luis Pperino Pomodoro !',
  when: '2 hs ago'},
  {title: 'Community X has a new member',
  description: '👋 Say hi to Luis Pperino Pomodoro !',
  when: '2 hs ago'},
];
